In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.19.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.05831589,  0.4958658 ,  0.20201182, -0.37591177, -0.44132483,
         0.12654807,  0.46681514, -0.22757837, -0.4183988 , -0.07627487]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09203512, 0.16018862, 0.11940224, 0.06699208, 0.06275018,
        0.11072329, 0.15560198, 0.07770409, 0.06420541, 0.09039702]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.200721)

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8612 - loss: 0.4823
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9560 - loss: 0.1499
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9678 - loss: 0.1065
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9748 - loss: 0.0857
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9772 - loss: 0.0731


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9756 - loss: 0.0754


[0.07540107518434525, 0.975600004196167]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.15113985e-07, 1.79259523e-08, 6.18958438e-06, 6.56457196e-05,
        6.29110583e-11, 1.76789229e-07, 3.80281229e-13, 9.99920607e-01,
        1.18531011e-06, 5.85329963e-06],
       [1.18671274e-07, 1.30551940e-04, 9.99798238e-01, 5.52506535e-05,
        2.90366079e-14, 1.34212678e-06, 1.01357109e-07, 3.60429265e-12,
        1.44517935e-05, 2.17940271e-12],
       [1.66983716e-06, 9.93501365e-01, 1.05970888e-03, 7.65502336e-05,
        2.87604140e-04, 1.99441420e-05, 1.98866415e-04, 3.34819569e-03,
        1.49979664e-03, 6.30352224e-06],
       [9.99727666e-01, 2.25867505e-10, 4.79295923e-05, 1.34319649e-07,
        1.29603537e-08, 5.71251167e-06, 1.91459367e-05, 5.61539650e-07,
        9.00342698e-08, 1.98679307e-04],
       [5.65892469e-06, 1.94569291e-10, 1.79701547e-05, 2.27010144e-08,
        9.98209238e-01, 4.58739322e-08, 7.78733920e-06, 5.61159413e-06,
        9.23809367e-08, 1.75359566e-03]], dtype=float32)>