In [ ]:
import torch

class TinyModel(torch.nn.Module):

    def __init__(self):
        super(TinyModel, self).__init__()

        self.linear1 = torch.nn.Linear(100, 200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200, 10)
        self.softmax = torch.nn.Softmax()

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel()

print('The model:')
print(tinymodel)

print('\n\nJust one layer:')
print(tinymodel.linear2)

print('\n\nModel params:')
for param in tinymodel.parameters():
    print(param)

print('\n\nLayer params:')
for param in tinymodel.linear2.parameters():
    print(param)

The model:
TinyModel(
  (linear1): Linear(in_features=100, out_features=200, bias=True)
  (activation): ReLU()
  (linear2): Linear(in_features=200, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)


Just one layer:
Linear(in_features=200, out_features=10, bias=True)


Model params:
Parameter containing:
tensor([[ 0.0561,  0.0246,  0.0624,  ..., -0.0031, -0.0114,  0.0493],
        [-0.0414,  0.0299, -0.0661,  ...,  0.0765,  0.0798, -0.0363],
        [-0.0823, -0.0369, -0.0339,  ..., -0.0789,  0.0189,  0.0478],
        ...,
        [-0.0859, -0.0460,  0.0657,  ...,  0.0142, -0.0779,  0.0139],
        [ 0.0481,  0.0052,  0.0249,  ..., -0.0309, -0.0445,  0.0780],
        [ 0.0749, -0.0790, -0.0628,  ..., -0.0365,  0.0267, -0.0299]],
       requires_grad=True)
Parameter containing:
tensor([-0.0856,  0.0489, -0.0135, -0.0646, -0.0709,  0.0477,  0.0537,  0.0158,
        -0.0439,  0.0209, -0.0576,  0.0733, -0.0738, -0.0926, -0.0827,  0.0249,
        -0.0652, -0.0667,  0.0283,  0.07

In [ ]:
lin = torch.nn.Linear(3, 2)
x = torch.rand(1, 3)
print('Input:')
print(x)

print('\n\nWeight and Bias parameters:')
for param in lin.parameters():
    print(param)

y = lin(x)
print('\n\nOutput:')
print(y)

Input:
tensor([[0.0382, 0.8962, 0.8986]])


Weight and Bias parameters:
Parameter containing:
tensor([[-0.4875, -0.2863,  0.1644],
        [-0.2794,  0.3093, -0.0810]], requires_grad=True)
Parameter containing:
tensor([0.2624, 0.0766], requires_grad=True)


Output:
tensor([[0.1348, 0.2703]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch.functional as F


class LeNet(torch.nn.Module):

    def __init__(self):
        super(LeNet, self).__init__()
        # 1 input image channel (black & white), 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = torch.nn.Conv2d(1, 6, 5)
        self.conv2 = torch.nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = torch.nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [ ]:
class LSTMTagger(torch.nn.Module):

    def __init__(self, embedding_dim, hidden_dim, vocab_size, tagset_size):
        super(LSTMTagger, self).__init__()
        self.hidden_dim = hidden_dim

        self.word_embeddings = torch.nn.Embedding(vocab_size, embedding_dim)

        # The LSTM takes word embeddings as inputs, and outputs hidden states
        # with dimensionality hidden_dim.
        self.lstm = torch.nn.LSTM(embedding_dim, hidden_dim)

        # The linear layer that maps from hidden state space to tag space
        self.hidden2tag = torch.nn.Linear(hidden_dim, tagset_size)

    def forward(self, sentence):
        embeds = self.word_embeddings(sentence)
        lstm_out, _ = self.lstm(embeds.view(len(sentence), 1, -1))
        tag_space = self.hidden2tag(lstm_out.view(len(sentence), -1))
        tag_scores = F.log_softmax(tag_space, dim=1)
        return tag_scores

In [ ]:
my_tensor = torch.rand(1, 6, 6)
print(my_tensor)

maxpool_layer = torch.nn.MaxPool2d(3)
print(maxpool_layer(my_tensor))

tensor([[[0.6476, 0.3397, 0.1132, 0.6026, 0.2618, 0.3625],
         [0.0430, 0.2864, 0.4704, 0.3619, 0.8202, 0.3691],
         [0.5988, 0.6658, 0.5893, 0.5515, 0.4692, 0.1219],
         [0.7008, 0.7103, 0.2590, 0.1653, 0.6981, 0.1959],
         [0.4840, 0.0456, 0.2508, 0.8532, 0.5805, 0.8327],
         [0.2078, 0.6420, 0.3721, 0.1473, 0.3389, 0.8070]]])
tensor([[[0.6658, 0.8202],
         [0.7103, 0.8532]]])


In [ ]:
my_tensor = torch.rand(1, 4, 4) * 20 + 5
print(my_tensor)

print(my_tensor.mean())

norm_layer = torch.nn.BatchNorm1d(4)
normed_tensor = norm_layer(my_tensor)
print(normed_tensor)

print(normed_tensor.mean())

tensor([[[ 5.7684, 18.9557, 10.5500, 23.3625],
         [14.1807,  5.1023, 15.2959, 13.1531],
         [ 6.1406, 19.8278,  5.3774, 17.0029],
         [15.8121, 14.4119, 10.6463, 20.5659]]])
tensor(13.5096)
tensor([[[-1.2895,  0.6232, -0.5960,  1.2624],
         [ 0.5597, -1.7009,  0.8374,  0.3038],
         [-0.9274,  1.2072, -1.0464,  0.7666],
         [ 0.1276, -0.2668, -1.3274,  1.4665]]],
       grad_fn=<NativeBatchNormBackward0>)
tensor(-1.4901e-08, grad_fn=<MeanBackward0>)


In [ ]:
my_tensor = torch.rand(1, 4, 4)

dropout = torch.nn.Dropout(p=0.4)
print(dropout(my_tensor))
print(dropout(my_tensor))

tensor([[[0.0000, 1.4278, 0.7384, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.5488],
         [0.6868, 1.3794, 0.0000, 1.0119],
         [0.6353, 0.0000, 0.0000, 0.4164]]])
tensor([[[1.3680, 1.4278, 0.0000, 0.0000],
         [0.6438, 0.0000, 0.7920, 0.0000],
         [0.6868, 1.3794, 0.8986, 0.0000],
         [0.6353, 0.9509, 0.0000, 0.0000]]])
